// packages/angular/src/components/fields/number-field.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NarrativeInlineInputComponent } from '../inline-input.component';

@Component({
  selector: 'ns-number-field',
  standalone: true,
  imports: [CommonModule, NarrativeInlineInputComponent],
  template: `
    <ns-inline-input
      [fieldKey]="fieldKey"
      type="number"
      [placeholder]="placeholder"
      [defaultValue]="defaultValue"
      [suffix]="suffix"
      [sanitise]="sanitise"
      [inputClassName]="inputClassName"
      [className]="className"
      (confirm)="confirm.emit($event)"
      (change)="change.emit($event)"
      (focus)="focus.emit()"
      (blur)="blur.emit($event)"
    ></ns-inline-input>
  `,
})
export class NarrativeNumberFieldComponent {
  @Input({ required: true }) fieldKey!: string;
  @Input() placeholder?: string;
  @Input() defaultValue = '';
  @Input() suffix?: string;
  @Input() inputClassName?: string;
  @Input() className?: string;

  @Output() confirm = new EventEmitter<string>();
  @Output() change = new EventEmitter<string>();
  @Output() focus = new EventEmitter<void>();
  @Output() blur = new EventEmitter<string>();

  sanitise = (val: string) => val.replace(/[^\d.-]/g, '');
}

// packages/vue/src/components/fields/NumberField.vue
<script setup lang="ts">
import InlineInput from "../InlineInput.vue";

const props = defineProps<{
  fieldKey: string;
  placeholder?: string;
  defaultValue?: string;
  suffix?: string;
  inputClassName?: string;
  className?: string;
}>();

const emit = defineEmits<{
  (e: "confirm", value: string): void;
  (e: "change", value: string): void;
  (e: "focus"): void;
  (e: "blur", value: string): void;
}>();

const sanitiseNumber = (val: string) => val.replace(/[^\d.-]/g, "");
</script>

<template>
  <InlineInput
    v-bind="props"
    type="number"
    :sanitise="sanitiseNumber"
    @confirm="v => emit('confirm', v)"
    @change="v => emit('change', v)"
    @focus="emit('focus')"
    @blur="v => emit('blur', v)"
  />
</template>
