// packages/angular/src/components/narrative-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { NarrativeFormConfig, NarrativeFieldValues } from '@viveksinghind/narrative-form-core';
import { NarrativeFormStateService } from '../services/form-state.service';
import { NarrativeWelcomeScreenComponent } from './welcome-screen.component';
import { NarrativeLineComponent } from './line.component';
import { NarrativeDoneScreenComponent } from './done-screen.component';
import { NarrativeToastContainerComponent } from './toast-container.component';

@Component({
  selector: 'ns-narrative-form',
  standalone: true,
  imports: [
    CommonModule,
    NarrativeWelcomeScreenComponent,
    NarrativeLineComponent,
    NarrativeDoneScreenComponent,
    NarrativeToastContainerComponent
  ],
  template: `
    <div [ngClass]="['ns-form', className, layout === 'paragraph' ? 'ns-layout-paragraph' : 'ns-layout-lines']">
      <!-- Welcome Screen -->
      <ns-welcome-screen
        *ngIf="showWelcome"
        [welcome]="config.welcome!"
        [typewriter]="$any(config).typewriter"
        (start)="handleStart()"
      ></ns-welcome-screen>

      <!-- Form Fields -->
      <div *ngIf="showFields" class="ns-fields" role="form" aria-live="polite">
        <ng-container *ngFor="let field of config.fields">
          <ns-line
            *ngIf="snapshot.statuses[field.key] && snapshot.statuses[field.key] !== 'idle'"
            [field]="field"
            [status]="snapshot.statuses[field.key]"
            [value]="snapshot.values[field.key]"
            [allValues]="snapshot.values"
            [typewriter]="$any(config).typewriter"
            [editable]="editable !== false"
            [locked]="field.lockPrevious && snapshot.statuses[field.key] === 'active'"
            [editLabel]="editLabel"
            (typingComplete)="formState.activateField($event)"
            (confirm)="onConfirm($event)"
            (edit)="formState.editField($event)"
            (changeEvent)="onChange($event)"
            (focusEvent)="formState.focusField($event)"
          ></ns-line>
        </ng-container>
      </div>

      <!-- Done Screen -->
      <ns-done-screen
        *ngIf="showDone"
        [done]="config.done!"
        [typewriter]="$any(config).typewriter"
      ></ns-done-screen>

      <!-- Toast Container -->
      <ns-toast-container></ns-toast-container>
    </div>
  `,
  providers: [NarrativeFormStateService] // Local to this component instance
})
export class NarrativeFormComponent implements OnInit {
  @Input({ required: true }) config!: NarrativeFormConfig;
  @Input() editable = true;
  @Input() editLabel = 'Edit';
  @Input() className = '';
  @Input() layout: 'lines' | 'paragraph' = 'lines';

  @Output() completed = new EventEmitter<NarrativeFieldValues>();
  @Output() valuesChange = new EventEmitter<NarrativeFieldValues>();
  @Output() event = new EventEmitter<{ type: string; payload?: any }>();

  hasStarted = false;

  constructor(public formState: NarrativeFormStateService) {}

  get snapshot() {
    return this.formState.snapshot();
  }

  get showWelcome(): boolean {
    return !!this.config.welcome && !this.hasStarted;
  }

  get showDone(): boolean {
    return !!this.config.done && this.snapshot.isComplete;
  }

  get showFields(): boolean {
    if (this.showWelcome) return false;
    if (this.showDone) return false;
    return true;
  }

  ngOnInit() {
    if (!this.config || !this.config.fields) {
      throw new Error('NarrativeForm requires a valid config with fields.');
    }
    this.formState.initialize(this.config.fields);

    // If no welcome screen, start typing the first field immediately
    if (!this.config.welcome) {
      this.hasStarted = true;
      this.startFirstField();
    }
  }

  handleStart() {
    this.hasStarted = true;
    this.startFirstField();
  }

  private startFirstField() {
    const firstKey = this.config.fields[0]?.key;
    if (firstKey) {
      this.formState.startTyping(firstKey);
    }
  }

  onConfirm(event: { key: string; value: string }) {
    this.formState.confirmField(event.key, event.value);
    
    // Check if the current value update completes the form
    const currentValues = this.formState.getValues();
    this.valuesChange.emit(currentValues);
    this.event.emit({ type: 'field_confirmed', payload: { key: event.key, value: event.value } });

    if (this.formState.snapshot().isComplete) {
      this.completed.emit(currentValues);
      this.event.emit({ type: 'form_completed', payload: currentValues });
    } else {
      // Find the next unconfirmed field and start its typing animation
      const currentIndex = this.config.fields.findIndex(f => f.key === event.key);
      for (let i = currentIndex + 1; i < this.config.fields.length; i++) {
        const nextField = this.config.fields[i];
        if (!nextField || this.snapshot.statuses[nextField.key] === 'confirmed') continue;
        this.formState.startTyping(nextField.key);
        break;
      }
    }
  }

  onChange(event: { key: string; value: string }) {
    this.event.emit({ type: 'field_change', payload: { key: event.key, value: event.value } });
  }
}

// packages/vue/src/components/NarrativeForm.vue
<script setup lang="ts">
import { computed, watch, ref, onMounted, nextTick } from "vue";
import type {
  NarrativeField,
  NarrativeTypewriter,
  NarrativeWelcome,
  NarrativeDone,
  NarrativeCallbacks,
  NarrativeFieldValues,
  NarrativeI18n,
  NarrativeFormConfig,
} from "@viveksinghind/narrative-form-core";
import { mergeStrings } from "@viveksinghind/narrative-form-core";
import { useFormState } from "../composables/useFormState";
import WelcomeScreen from "./WelcomeScreen.vue";
import DoneScreen from "./DoneScreen.vue";
import Line from "./Line.vue";

const props = withDefaults(defineProps<{
  fields?: NarrativeField[];
  formConfig?: NarrativeFormConfig;
  typewriter?: NarrativeTypewriter;
  welcome?: NarrativeWelcome;
  done?: NarrativeDone;
  editable?: boolean;
  editLabel?: string;
  callbacks?: NarrativeCallbacks;
  defaultValues?: NarrativeFieldValues;
  values?: NarrativeFieldValues;
  strings?: Partial<NarrativeI18n>;
  reducedMotion?: boolean;
  layout?: "lines" | "paragraph";
}>(), {
  editable: true,
  layout: "lines"
});

const resolvedFields = computed(() => {
  if (props.fields) return props.fields;
  if (props.formConfig) return props.formConfig.fields;
  return [];
});

const resolvedWelcome = computed(() => {
  if (props.welcome) return props.welcome;
  if (props.formConfig && "welcome" in props.formConfig) return (props.formConfig as any).welcome;
  return undefined;
});

const resolvedDone = computed(() => {
  if (props.done) return props.done;
  if (props.formConfig && "done" in props.formConfig) return (props.formConfig as any).done;
  return undefined;
});

const effectiveTypewriter = computed<NarrativeTypewriter>(() => ({
  ...props.typewriter,
  enabled: props.reducedMotion ? false : (props.typewriter?.enabled ?? true),
}));

const i18n = computed(() => mergeStrings(props.strings));

const {
  snapshot,
  startTyping,
  activateField,
  confirmField,
  editField,
  reconfirmField,
  getMeta,
} = useFormState(resolvedFields.value);

const showWelcome = computed(() => resolvedWelcome.value?.show !== false && resolvedWelcome.value !== undefined);
const welcomeDismissed = ref(!showWelcome.value);
const hasStarted = ref(false);

const startFirstField = () => {
  if (!welcomeDismissed.value || hasStarted.value || resolvedFields.value.length === 0) return;
  hasStarted.value = true;
  const firstField = resolvedFields.value.find((f) => snapshot.value.statuses[f.key] !== "confirmed");
  if (firstField) {
    startTyping(firstField.key);
  }
};

watch(welcomeDismissed, startFirstField);
onMounted(startFirstField);

const handleConfirm = (key: string, value: string) => {
  const status = snapshot.value.statuses[key];
  if (status === "editing") {
    reconfirmField(key, value);
  } else {
    confirmField(key, value);
  }
  
  if (props.callbacks?.onFieldComplete) {
    props.callbacks.onFieldComplete(key, value, 0);
  }

  const currentIndex = resolvedFields.value.findIndex((f) => f.key === key);
  for (let i = currentIndex + 1; i < resolvedFields.value.length; i++) {
    const nextField = resolvedFields.value[i];
    if (!nextField || snapshot.value.statuses[nextField.key] === "confirmed") continue;
    startTyping(nextField.key);
    break;
  }
};

const visibleFields = computed(() => {
  return resolvedFields.value.filter((field) => {
    const status = snapshot.value.statuses[field.key];
    return status === "typing" || status === "active" || status === "confirmed" || status === "editing";
  });
});

const scrollContainerRef = ref<HTMLElement | null>(null);

watch(() => visibleFields.value.length, () => {
  nextTick(() => {
    if (scrollContainerRef.value) {
      scrollContainerRef.value.scrollTop = scrollContainerRef.value.scrollHeight;
    }
  });
});

</script>

<template>
    <div :class="['ns-root', layout === 'paragraph' ? 'ns-layout-paragraph' : 'ns-layout-lines']" ref="scrollContainerRef">
      <WelcomeScreen
        v-if="!welcomeDismissed && resolvedWelcome"
        :welcome="resolvedWelcome"
        :typewriter="effectiveTypewriter"
        @start="welcomeDismissed = true"
      />

    <div v-if="welcomeDismissed" class="ns-form-body">
      <Line
        v-for="field in visibleFields"
        :key="field.key"
        :field="field"
        :status="snapshot.statuses[field.key] ?? 'idle'"
        :value="props.values?.[field.key] ?? snapshot.values[field.key]"
        :allValues="snapshot.values"
        :typewriter="effectiveTypewriter"
        :editable="props.editable"
        :locked="false"
        :editLabel="props.editLabel ?? i18n.editLabel"
        @typingComplete="activateField"
        @confirm="handleConfirm"
        @edit="k => { editField(k); props.callbacks?.onEdit?.(k); }"
        @error="(k, err) => props.callbacks?.onError?.(k, err)"
        @change="(k, v) => props.callbacks?.onChange?.(k, v)"
        @focus="k => props.callbacks?.onFieldFocus?.(k)"
        @blur="(k, v) => props.callbacks?.onFieldBlur?.(k, v)"
      />
    </div>

    <DoneScreen
      v-if="snapshot.isComplete && resolvedDone"
      :done="resolvedDone"
      :values="snapshot.values"
      :meta="getMeta()"
      :typewriter="effectiveTypewriter"
    />
  </div>
</template>

<style scoped>
.ns-root {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow-y: auto;
  padding: 1.25rem;
}
.ns-layout-lines .ns-form-body {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}
.ns-layout-paragraph .ns-form-body {
  display: block;
  flex-grow: 1;
}
</style>
