// packages/vue/src/components/EnterButton.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<{
  label?: string;
  className?: string;
}>(), {
  label: "↵",
});

const emit = defineEmits<{
  (e: "confirm"): void;
}>();

const classes = computed(() => {
  return ["ns-enter-btn", props.className].filter(Boolean).join(" ");
});
</script>

<template>
  <button
    type="button"
    :class="classes"
    @click="emit('confirm')"
    aria-label="Confirm"
  >
    {{ label }}
  </button>
</template>

// packages/angular/src/components/enter-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ns-enter-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      type="button"
      [ngClass]="['ns-enter-btn', className || '']"
      (click)="onClick()"
      aria-label="Confirm"
    >
      {{ label }}
    </button>
  `,
})
export class NarrativeEnterButtonComponent {
  @Input() label = '↵';
  @Input() className?: string;
  @Output() confirm = new EventEmitter<void>();

  onClick() {
    this.confirm.emit();
  }
}
