// packages/vue/src/components/FilledValue.vue
<script setup lang="ts">
import { computed } from "vue";
import EditIcon from "./EditIcon.vue";

const props = withDefaults(defineProps<{
  value: string;
  suffix?: string;
  editable?: boolean;
  editLabel?: string;
  className?: string;
}>(), {
  editable: true,
  editLabel: "Edit",
});

const emit = defineEmits<{
  (e: "edit"): void;
}>();

const classes = computed(() => ["ns-filled-wrap", props.className].filter(Boolean).join(" "));
</script>

<template>
  <span :class="classes">
    <span class="ns-filled-value">{{ value }}</span>
    <span v-if="suffix" class="ns-suffix">{{ suffix }}</span>
    <EditIcon
      v-if="editable"
      :label="editLabel"
      @edit="emit('edit')"
    />
  </span>
</template>

// packages/angular/src/components/filled-value.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ns-filled-value',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span class="ns-filled-wrap">
      <span class="ns-filled-value">{{ value }}</span>
      <span *ngIf="suffix" class="ns-suffix">{{ suffix }}</span>
      <button
        *ngIf="editable"
        type="button"
        class="ns-edit-btn"
        (click)="onEditClick()"
        [attr.aria-label]="editLabel"
      >
        ✎
      </button>
    </span>
  `,
})
export class NarrativeFilledValueComponent {
  @Input({ required: true }) value!: string;
  @Input() suffix?: string;
  @Input() editable = true;
  @Input() editLabel = 'Edit';

  @Output() edit = new EventEmitter<void>();

  onEditClick() {
    this.edit.emit();
  }
}
