// packages/react/src/components/Line.tsx
/**
 * Line — single sentence row orchestrator for narrative-form.
 *
 * @remarks
 * Manages the full lifecycle of a single field within the form:
 * `typing → active → confirmed → editing`.
 *
 * Composes: Prose + InlineInput (or FilledValue + EditIcon) + ErrorMessage.
 * Runs validation on confirm — blocks confirmation if validation fails.
 * Supports async validation with loading/success visual states.
 * CSS classes: `ns-line`, `ns-line--active`, `ns-line--confirmed`,
 * `ns-line--editing`, `ns-line--error`, `ns-line-[key]`
 */

import React, { useCallback, useState, useRef } from "react";
import type { NarrativeField, NarrativeTypewriter, NarrativeFieldValues } from "@viveksinghind/narrative-form-core";
import type { FieldStatus } from "@viveksinghind/narrative-form-core";
import { validateField, validateFieldAsync, hasAsyncValidation } from "@viveksinghind/narrative-form-core";
import { Prose } from "./Prose";
import { InlineInput } from "./InlineInput";
import { FilledValue } from "./FilledValue";
import { ErrorMessage } from "./ErrorMessage";
import { ChipsField } from "./fields/ChipsField";
import { MultiChipsField } from "./fields/MultiChipsField";
import { SelectField } from "./fields/SelectField";
import { OtpField } from "./fields/OtpField";
import { PasswordField } from "./fields/PasswordField";
import { DateField } from "./fields/DateField";
import { useToast } from "./ToastProvider";

/** Async validation visual state. */
type AsyncState = "idle" | "validating" | "valid" | "invalid";

/** Props for the Line component. */
export interface LineProps {
  /** The field configuration for this line. */
  field: NarrativeField;
  /** Current lifecycle status of this field. */
  status: FieldStatus;
  /** The confirmed value (if any). */
  value?: string | string[];
  /** All confirmed values so far (for cross-field validation). */
  allValues?: NarrativeFieldValues;
  /** Typewriter configuration. */
  typewriter?: NarrativeTypewriter;
  /** Whether editing is enabled globally. Default: true */
  editable?: boolean;
  /** Whether this field is locked (lockPrevious). */
  locked?: boolean;
  /** Label for the edit button. */
  editLabel?: string;
  /** Called when typing animation completes — field should become active. */
  onTypingComplete: (key: string) => void;
  /** Called when the field value is confirmed (after validation passes). */
  onConfirm: (key: string, value: string) => void;
  /** Called when the edit icon is clicked. */
  onEdit: (key: string) => void;
  /** Called when validation fails. */
  onError?: (key: string, message: string) => void;
  /** Called on every keystroke. */
  onChange?: (key: string, value: string) => void;
  /** Called when input receives focus. */
  onFocus?: (key: string) => void;
  /** Called when input loses focus. */
  onBlur?: (key: string, value: string) => void;
}

/** Helper props for the field rendering function. */
interface RenderFieldInputProps {
  field: NarrativeField;
  status: FieldStatus;
  value?: string | string[];
  handleConfirm: (val: string) => void;
  handleChange: (val: string) => void;
  handleFocus: () => void;
  handleBlur: (val: string) => void;
  handlePaste?: (val: string) => string;
}

/**
 * Renders the correct input component based on field type.
 */
function renderFieldInput({
  field,
  status,
  value,
  handleConfirm,
  handleChange,
  handleFocus,
  handleBlur,
}: RenderFieldInputProps): React.ReactNode {
  const editValue =
    status === "editing" && value !== undefined ? String(value) : field.defaultValue;

  switch (field.type) {
    case "chips":
      return (
        <ChipsField
          fieldKey={field.key}
          options={field.options ?? []}
          defaultValue={editValue}
          autoAdvance={field.autoAdvance}
          onConfirm={handleConfirm}
          onChange={handleChange}
          className={field.inputClassName}
        />
      );

    case "multi-chips":
      return (
        <MultiChipsField
          fieldKey={field.key}
          options={field.options ?? []}
          defaultValue={
            status === "editing" && Array.isArray(value)
              ? value
              : editValue?.split(", ").filter(Boolean)
          }
          onConfirm={handleConfirm}
          onChange={handleChange}
          className={field.inputClassName}
        />
      );

    case "select":
      return (
        <SelectField
          fieldKey={field.key}
          options={field.options ?? []}
          placeholder={field.placeholder}
          defaultValue={editValue}
          autoAdvance={field.autoAdvance}
          onConfirm={handleConfirm}
          onChange={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
          inputClassName={field.inputClassName}
        />
      );

    case "otp":
      return (
        <OtpField
          fieldKey={field.key}
          otpLength={field.otpLength}
          autoAdvance={field.autoAdvance ?? true}
          onRequest={field.onRequest}
          onVerify={field.onVerify}
          onConfirm={handleConfirm}
          onChange={handleChange}
          resendLabel={field.resendLabel}
          resendDelay={field.resendDelay}
          className={field.inputClassName}
        />
      );

    case "password":
      return (
        <PasswordField
          fieldKey={field.key}
          placeholder={field.placeholder}
          defaultValue={editValue}
          suffix={field.suffix}
          onConfirm={handleConfirm}
          onChange={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
          inputClassName={field.inputClassName}
        />
      );

    case "date":
      return (
        <DateField
          fieldKey={field.key}
          placeholder={field.placeholder}
          defaultValue={editValue}
          suffix={field.suffix}
          onConfirm={handleConfirm}
          onChange={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
          inputClassName={field.inputClassName}
        />
      );

    // text, tel, email, number — all use InlineInput with the appropriate type
    default:
      return (
        <InlineInput
          fieldKey={field.key}
          type={field.type}
          placeholder={field.placeholder}
          defaultValue={editValue}
          suffix={field.suffix}
          sanitise={field.sanitise}
          onConfirm={handleConfirm}
          onChange={handleChange}
          onFocus={handleFocus}
          onBlur={handleBlur}
          inputClassName={field.inputClassName}
        />
      );
  }
}

/**
 * Renders a single sentence row — the core building block of the narrative form.
 *
 * Lifecycle:
 * 1. `typing` — Prose types out the prefix text
 * 2. `active` — Input appears for the user to fill
 * 3. `confirmed` — Value is locked, shown as filled text with edit icon
 * 4. `editing` — User clicked edit, input re-appears with current value
 *
 * Validation runs on confirm. If it fails, the field stays active and
 * an error message is displayed below the input.
 *
 * @param props - Line configuration
 */
export const Line: React.FC<LineProps> = React.memo(function Line({
  field,
  status,
  value,
  allValues = {},
  typewriter,
  editable = true,
  locked = false,
  editLabel = "Edit",
  onTypingComplete,
  onConfirm,
  onEdit,
  onError,
  onChange,
  onFocus,
  onBlur,
}) {
  const [error, setError] = useState<string | null>(null);
  const [shake, setShake] = useState(false);
  const [asyncState, setAsyncState] = useState<AsyncState>("idle");
  const abortRef = useRef<(() => void) | null>(null);
  const { showToast } = useToast();

  const isFieldEditable = field.editable !== false && editable && !locked;
  const shouldAnimate = field.animate !== false && (typewriter?.enabled !== false);

  const handleTypingComplete = useCallback(() => {
    onTypingComplete(field.key);
  }, [field.key, onTypingComplete]);

  const handleConfirm = useCallback(
    (val: string) => {
      // Abort any in-flight async validation
      abortRef.current?.();
      abortRef.current = null;

      // Run sync validation first
      const result = validateField(val, field.validation, allValues);

      if (!result.valid) {
        const firstError = result.errors[0] ?? "Validation failed";
        setError(firstError);
        setAsyncState("idle");
        onError?.(field.key, firstError);

        const display = field.validation?.errorDisplay;
        const mode = display?.mode ?? "inline";

        if (mode === "shake" || mode === "inline+shake") {
          setShake(false);
          setTimeout(() => setShake(true), 10);
        }

        if (mode === "toast") {
          showToast(firstError, display?.icon, display?.iconChar);
        }

        return; // Block confirmation
      }

      // Check if async validation is needed
      if (hasAsyncValidation(field.validation)) {
        setAsyncState("validating");
        setError(null);

        const handle = validateFieldAsync(val, field.validation, allValues);
        abortRef.current = handle.abort;

        handle.promise
          .then((asyncResult) => {
            if (!asyncResult.valid) {
              const firstError = asyncResult.errors[0] ?? "Validation failed";
              setError(firstError);
              setAsyncState("invalid");
              onError?.(field.key, firstError);
            } else {
              setAsyncState("valid");
              setError(null);
              // Short delay to show success before confirming
              setTimeout(() => {
                setAsyncState("idle");
                onConfirm(field.key, val);
              }, 300);
            }
          })
          .catch(() => {
            // Aborted or unexpected error — reset silently
            setAsyncState("idle");
          });

        return; // Don't confirm yet — wait for async
      }

      // Sync validation passed, no async — confirm
      setError(null);
      setShake(false);
      setAsyncState("idle");
      onConfirm(field.key, val);
    },
    [field.key, field.validation, allValues, onConfirm, onError, showToast],
  );

  const handleEdit = useCallback(() => {
    setError(null);
    setShake(false);
    setAsyncState("idle");
    abortRef.current?.();
    onEdit(field.key);
  }, [field.key, onEdit]);

  const handleChange = useCallback(
    (val: string) => {
      const clearOn = field.validation?.errorDisplay?.clearOn ?? "onChange";
      if (clearOn === "onChange" && error !== null) {
        setError(null);
        setShake(false);
        setAsyncState("idle");
      }
      onChange?.(field.key, val);
    },
    [field.key, onChange, error, field.validation?.errorDisplay?.clearOn],
  );

  const handleFocus = useCallback(() => {
    const clearOn = field.validation?.errorDisplay?.clearOn ?? "onChange";
    if (clearOn === "onFocus" && error !== null) {
      setError(null);
      setShake(false);
      setAsyncState("idle");
    }
    onFocus?.(field.key);
  }, [field.key, onFocus, error, field.validation?.errorDisplay?.clearOn]);

  const handleBlur = useCallback(
    (val: string) => {
      onBlur?.(field.key, val);
    },
    [field.key, onBlur],
  );

  // Build CSS class list
  const lineClasses = [
    "ns-line",
    `ns-line-${field.key}`,
    status === "active" || status === "editing" ? "ns-line--active" : undefined,
    status === "confirmed" ? "ns-line--confirmed" : undefined,
    status === "editing" ? "ns-line--editing" : undefined,
    error !== null ? "ns-line--error" : undefined,
    shake ? "ns-line--shake" : undefined,
    field.className,
  ]
    .filter(Boolean)
    .join(" ");

  // Determine what to show based on status
  const showInput = status === "active" || status === "editing";
  const showFilled = status === "confirmed";

  return (
    <div className={lineClasses} role="group" aria-label={field.prefix}>
      <Prose
        text={field.prefix}
        animate={status === "typing" && shouldAnimate}
        speed={typewriter?.speed}
        cursor={typewriter?.cursor}
        cursorChar={typewriter?.cursorChar}
        pauseAfter={typewriter?.pauseAfter}
        onComplete={status === "typing" ? handleTypingComplete : undefined}
      />

      {/* Show input when field is active or being edited */}
      {showInput && renderFieldInput({
        field,
        status,
        value,
        handleConfirm,
        handleChange,
        handleFocus,
        handleBlur,
      })}

      {/* Async validation indicators */}
      {showInput && asyncState === "validating" && (
        <span className="ns-loading-indicator" aria-label="Validating" />
      )}
      {showInput && asyncState === "valid" && (
        <span className="ns-success-indicator" aria-label="Valid">✓</span>
      )}

      {/* Show filled value when confirmed */}
      {showFilled && (
        <FilledValue
          value={String(value ?? "")}
          suffix={field.suffix}
          editable={isFieldEditable}
          onEdit={handleEdit}
          editLabel={editLabel}
        />
      )}

      {/* Show validation error */}
      {error !== null && showInput && (
        <ErrorMessage
          message={error}
          display={field.validation?.errorDisplay}
        />
      )}
    </div>
  );
});

// packages/angular/src/components/line.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NarrativeField, NarrativeTypewriter, NarrativeFieldValues, FieldStatus, validateField, validateFieldAsync, hasAsyncValidation } from '@viveksinghind/narrative-form-core';
import { NarrativeToastService } from '../services/toast.service';

import { NarrativeProseComponent } from './prose.component';
import { NarrativeFilledValueComponent } from './filled-value.component';
import { NarrativeErrorMessageComponent } from './error-message.component';
import { NarrativeInlineInputComponent } from './inline-input.component';
import { NarrativePasswordFieldComponent } from './fields/password-field.component';
import { NarrativeDateFieldComponent } from './fields/date-field.component';
import { NarrativeSelectFieldComponent } from './fields/select-field.component';
import { NarrativeOtpFieldComponent } from './fields/otp-field.component';
import { NarrativeChipsFieldComponent } from './fields/chips-field.component';
import { NarrativeMultiChipsFieldComponent } from './fields/multi-chips-field.component';

@Component({
  selector: 'ns-line',
  standalone: true,
  imports: [
    CommonModule,
    NarrativeProseComponent,
    NarrativeFilledValueComponent,
    NarrativeErrorMessageComponent,
    NarrativeInlineInputComponent,
    NarrativePasswordFieldComponent,
    NarrativeDateFieldComponent,
    NarrativeSelectFieldComponent,
    NarrativeOtpFieldComponent,
    NarrativeChipsFieldComponent,
    NarrativeMultiChipsFieldComponent,
  ],
  template: `
    <div [ngClass]="lineClasses" role="group" [attr.aria-label]="field.prefix">
      <ns-prose
        [text]="field.prefix"
        [animate]="status === 'typing' && shouldAnimate"
        [speed]="typewriter?.speed || 38"
        [cursor]="typewriter?.cursor !== false"
        [cursorChar]="typewriter?.cursorChar || '|'"
        [pauseAfter]="typewriter?.pauseAfter || 100"
        (complete)="onTypingCompleteEvent()"
      ></ns-prose>

      <ng-container *ngIf="showInput">
        <ng-container [ngSwitch]="field.type">
          <ns-chips-field
            *ngSwitchCase="'chips'"
            [fieldKey]="field.key"
            [options]="field.options || []"
            [defaultValue]="editValue"
            [autoAdvance]="field.autoAdvance || false"
            [className]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
          ></ns-chips-field>

          <ns-multi-chips-field
            *ngSwitchCase="'multi-chips'"
            [fieldKey]="field.key"
            [options]="field.options || []"
            [defaultValue]="multiEditValue"
            [className]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
          ></ns-multi-chips-field>

          <ns-select-field
            *ngSwitchCase="'select'"
            [fieldKey]="field.key"
            [options]="field.options || []"
            [placeholder]="field.placeholder"
            [defaultValue]="editValue"
            [autoAdvance]="field.autoAdvance || false"
            [inputClassName]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
            (focus)="handleFocus()"
            (blur)="handleBlur($event)"
          ></ns-select-field>

          <ns-otp-field
            *ngSwitchCase="'otp'"
            [fieldKey]="field.key"
            [otpLength]="field.otpLength || 6"
            [autoAdvance]="field.autoAdvance !== false"
            [resendLabel]="field.resendLabel || 'Resend code'"
            [resendDelay]="field.resendDelay || 30"
            [className]="field.inputClassName"
            (request)="field.onRequest && field.onRequest()"
            (verify)="field.onVerify && field.onVerify($event)"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
          ></ns-otp-field>

          <ns-password-field
            *ngSwitchCase="'password'"
            [fieldKey]="field.key"
            [placeholder]="field.placeholder"
            [defaultValue]="editValue"
            [suffix]="field.suffix"
            [inputClassName]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
            (focus)="handleFocus()"
            (blur)="handleBlur($event)"
          ></ns-password-field>

          <ns-date-field
            *ngSwitchCase="'date'"
            [fieldKey]="field.key"
            [placeholder]="field.placeholder"
            [defaultValue]="editValue"
            [suffix]="field.suffix"
            [inputClassName]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
            (focus)="handleFocus()"
            (blur)="handleBlur($event)"
          ></ns-date-field>

          <ns-inline-input
            *ngSwitchDefault
            [fieldKey]="field.key"
            [type]="field.type"
            [placeholder]="field.placeholder"
            [defaultValue]="editValue"
            [suffix]="field.suffix"
            [sanitise]="field.sanitise"
            [inputClassName]="field.inputClassName"
            (confirm)="handleConfirm($event)"
            (change)="handleChange($event)"
            (focus)="handleFocus()"
            (blur)="handleBlur($event)"
          ></ns-inline-input>
        </ng-container>
      </ng-container>

      <span *ngIf="showInput && asyncState === 'validating'" class="ns-loading-indicator" aria-label="Validating"></span>
      <span *ngIf="showInput && asyncState === 'valid'" class="ns-success-indicator" aria-label="Valid">✓</span>

      <ns-filled-value
        *ngIf="showFilled"
        [value]="displayValue"
        [suffix]="field.suffix"
        [editable]="isFieldEditable"
        [editLabel]="editLabel"
        (edit)="handleEdit()"
      ></ns-filled-value>

      <ns-error-message
        *ngIf="error !== null && showInput"
        [message]="error"
        [mode]="field.validation?.errorDisplay?.mode || 'inline'"
        [position]="field.validation?.errorDisplay?.position || 'below'"
        [icon]="field.validation?.errorDisplay?.icon !== false"
        [iconChar]="field.validation?.errorDisplay?.iconChar || '⚠'"
      ></ns-error-message>
    </div>
  `,
})
export class NarrativeLineComponent implements OnDestroy {
  @Input({ required: true }) field!: NarrativeField;
  @Input({ required: true }) status!: FieldStatus;
  @Input() value?: string | string[];
  @Input() allValues: NarrativeFieldValues = {};
  @Input() typewriter?: NarrativeTypewriter;
  @Input() editable = true;
  @Input() locked = false;
  @Input() editLabel = 'Edit';

  @Output() typingComplete = new EventEmitter<string>();
  @Output() confirm = new EventEmitter<{ key: string; value: string }>();
  @Output() edit = new EventEmitter<string>();
  @Output() errorChange = new EventEmitter<{ key: string; message: string }>();
  @Output() changeEvent = new EventEmitter<{ key: string; value: string }>();
  @Output() focusEvent = new EventEmitter<string>();
  @Output() blurEvent = new EventEmitter<{ key: string; value: string }>();

  error: string | null = null;
  shake = false;
  asyncState: 'idle' | 'validating' | 'valid' | 'invalid' = 'idle';

  private abortRef: (() => void) | null = null;

  constructor(private toastService: NarrativeToastService) {}

  ngOnDestroy() {
    if (this.abortRef) {
      this.abortRef();
    }
  }

  get isFieldEditable(): boolean {
    return this.field.editable !== false && this.editable && !this.locked;
  }

  get shouldAnimate(): boolean {
    return this.field.animate !== false && this.typewriter?.enabled !== false;
  }

  get editValue(): string {
    return this.status === 'editing' && this.value !== undefined
      ? String(this.value)
      : (this.field.defaultValue || '');
  }

  get multiEditValue(): string[] {
    if (this.status === 'editing' && Array.isArray(this.value)) {
      return this.value;
    }
    return (this.field.defaultValue || '').split(', ').filter(Boolean);
  }

  get displayValue(): string {
    return String(this.value || '');
  }

  get showInput(): boolean {
    return this.status === 'active' || this.status === 'editing';
  }

  get showFilled(): boolean {
    return this.status === 'confirmed';
  }

  get lineClasses(): string {
    return [
      'ns-line',
      `ns-line-${this.field.key}`,
      this.status === 'active' || this.status === 'editing' ? 'ns-line--active' : '',
      this.status === 'confirmed' ? 'ns-line--confirmed' : '',
      this.status === 'editing' ? 'ns-line--editing' : '',
      this.error !== null ? 'ns-line--error' : '',
      this.shake ? 'ns-line--shake' : '',
      this.field.className || ''
    ].filter(Boolean).join(' ');
  }

  onTypingCompleteEvent() {
    if (this.status === 'typing') {
      this.typingComplete.emit(this.field.key);
    }
  }

  handleConfirm(val: string) {
    if (this.abortRef) {
      this.abortRef();
      this.abortRef = null;
    }

    const result = validateField(val, this.field.validation, this.allValues);

    if (!result.valid) {
      const firstError = result.errors[0] || 'Validation failed';
      this.error = firstError;
      this.asyncState = 'idle';
      this.errorChange.emit({ key: this.field.key, message: firstError });

      const display = this.field.validation?.errorDisplay;
      const mode = display?.mode || 'inline';

      if (mode === 'shake' || mode === 'inline+shake') {
        this.shake = false;
        setTimeout(() => (this.shake = true), 10);
      }

      if (mode === 'toast') {
        this.toastService.showToast(firstError, display?.icon !== false, display?.iconChar || '⚠');
      }

      return;
    }

    if (hasAsyncValidation(this.field.validation)) {
      this.asyncState = 'validating';
      this.error = null;

      const handle = validateFieldAsync(val, this.field.validation, this.allValues);
      this.abortRef = handle.abort;

      handle.promise
        .then((asyncResult) => {
          if (!asyncResult.valid) {
            const firstError = asyncResult.errors[0] || 'Validation failed';
            this.error = firstError;
            this.asyncState = 'invalid';
            this.errorChange.emit({ key: this.field.key, message: firstError });
          } else {
            this.asyncState = 'valid';
            this.error = null;
            setTimeout(() => {
              this.asyncState = 'idle';
              this.confirm.emit({ key: this.field.key, value: val });
            }, 300);
          }
        })
        .catch(() => {
          this.asyncState = 'idle';
        });

      return;
    }

    this.error = null;
    this.shake = false;
    this.asyncState = 'idle';
    this.confirm.emit({ key: this.field.key, value: val });
  }

  handleEdit() {
    this.error = null;
    this.shake = false;
    this.asyncState = 'idle';
    if (this.abortRef) {
      this.abortRef();
    }
    this.edit.emit(this.field.key);
  }

  handleChange(val: string) {
    const clearOn = this.field.validation?.errorDisplay?.clearOn || 'onChange';
    if (clearOn === 'onChange' && this.error !== null) {
      this.error = null;
      this.shake = false;
      this.asyncState = 'idle';
    }
    this.changeEvent.emit({ key: this.field.key, value: val });
  }

  handleFocus() {
    const clearOn = this.field.validation?.errorDisplay?.clearOn || 'onChange';
    if (clearOn === 'onFocus' && this.error !== null) {
      this.error = null;
      this.shake = false;
      this.asyncState = 'idle';
    }
    this.focusEvent.emit(this.field.key);
  }

  handleBlur(val: string) {
    this.blurEvent.emit({ key: this.field.key, value: val });
  }
}
